name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2.4.0
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Set up JDK (GraalVM)
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: 1.18.2-Purpur"
      - name: Pull Gradle Cache
        uses: actions/cache@v3.0.1
        id: gradle-cache
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-maven-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-java-17
      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
      - name: Patch
        run: |
          ./gradlew -Dorg.gradle.jvmargs="-Dfile.encoding=UTF-8 -Djdk.nio.maxCachedBufferSize=262144 -Dgraal.CompilerConfiguration=community -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true -Dgraal.SpeculativeGuardMovement=true -Dgraal.WriteableCodeCache=true --add-modules jdk.incubator.vector" applyPatches --stacktrace --no-daemon
      - name: Build
        run: |
          ./gradlew -Dorg.gradle.jvmargs="-Dfile.encoding=UTF-8 -Djdk.nio.maxCachedBufferSize=262144 -Dgraal.CompilerConfiguration=community -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true -Dgraal.SpeculativeGuardMovement=true -Dgraal.WriteableCodeCache=true --add-modules jdk.incubator.vector" createReobfPaperclipJar --stacktrace --no-daemon
      - name: Archive Paperclip
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Mirai-Purpur-1.18.2
          path: build/libs/mirai-paperclip-1.18.2-R0.1-SNAPSHOT-reobf.jar
      
      
          
      - name: releases-action
        # 您可以固定到确切的提交或版本.
        uses: nickatnight/releases-action@v2
        with:
          # 要发布的分支的名称
          branch: 'ver/1.18.2'
          # 发布名称
          name: 'Mirai-Purpur'
          # 发布消息
          message: '发布消息'
          # 草稿还是瑙？
          draft: false
          # 预发布或新版本
          prerelease: false
          # 标签名称
          tag: 'Mirai-Purpur'
